# Generated by Django 2.0.5 on 2018-06-15 21:13

import django.core.validators
from django.db import migrations, models
import enumfields.fields
import wallet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.URLValidator()], verbose_name='short name')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('currency', enumfields.fields.EnumField(enum=wallet.models.Currency, max_length=10, verbose_name='currency')),
                ('fee', models.IntegerField(default=0, verbose_name='transaction fee')),
                ('is_active', models.BooleanField(default=True, help_text='Designate whether this type of requests can be created.', verbose_name='active')),
            ],
        ),
    ]
