# Generated by Django 2.0.4 on 2018-08-24 11:55

import django.core.validators
from django.db import migrations, models
import proxypay.fields
import services.models
import wallet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('currency', proxypay.fields.EnumField(enum=wallet.models.Currency, max_length=3, verbose_name='currency')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', proxypay.fields.EnumField(default='PENDING', enum=services.models.RequestStatus, max_length=8, verbose_name='status')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\_\\-]+$')], verbose_name='short name')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('currency', proxypay.fields.EnumField(enum=wallet.models.Currency, max_length=3, verbose_name='currency')),
                ('fee', models.PositiveIntegerField(default=0, verbose_name='transaction fee')),
                ('is_active', models.BooleanField(default=True, help_text='Designate whether this type of requests can be created.', verbose_name='active')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
    ]
