# Generated by Django 2.0.5 on 2018-06-15 21:28

from django.db import migrations
import proxypay.fields
import wallet.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='currency',
            field=proxypay.fields.EnumField(enum=wallet.models.Currency, max_length=3, verbose_name='currency'),
        ),
    ]
