# Generated by Django 2.0.8 on 2018-08-19 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180615_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='fee',
            field=models.PositiveIntegerField(default=0, verbose_name='transaction fee'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='short_name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('[^\\s]*')], verbose_name='short name'),
        ),
    ]
