# Generated by Django 2.0.8 on 2018-08-19 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import proxypay.fields
import wallet.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180819_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='currency',
            field=proxypay.fields.EnumField(default=wallet.models.Currency.IRR, enum=wallet.models.Currency, max_length=3, verbose_name='currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='services.ServiceType', verbose_name='service type'),
        ),
    ]
