# Generated by Django 2.0.4 on 2018-08-26 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20180825_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='max_amount',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='max amount'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='min_amount',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='min amount'),
        ),
    ]
