# Generated by Django 2.0.4 on 2018-08-26 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20180826_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='link',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
    ]
