# Generated by Django 2.0.4 on 2018-08-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_servicetype_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='link',
        ),
    ]
