# Generated by Django 2.0.8 on 2018-08-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_servicetype_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
    ]
