# Generated by Django 2.0.8 on 2018-08-24 23:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180615_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
    ]
