# Generated by Django 2.0.5 on 2018-06-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='exchange_fee',
            field=models.IntegerField(default=0, verbose_name='exchange fee'),
        ),
        migrations.AlterField(
            model_name='config',
            name='index_content',
            field=models.TextField(default='', verbose_name='index content'),
        ),
    ]
