# Generated by Django 2.0.8 on 2018-08-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180626_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='exchange_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='exchange fee'),
        ),
        migrations.AlterField(
            model_name='config',
            name='index_content',
            field=models.TextField(blank=True, default='', verbose_name='index content'),
        ),
    ]
